// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Psi_from_H_cpp
Eigen::SparseMatrix<double> Psi_from_H_cpp(const Eigen::Map<Eigen::VectorXd> psi_mr, const Eigen::MappedSparseMatrix<double> H);
RcppExport SEXP _limestest_Psi_from_H_cpp(SEXP psi_mrSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type psi_mr(psi_mrSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(Psi_from_H_cpp(psi_mr, H));
    return rcpp_result_gen;
END_RCPP
}
// loglik_psi_cpp
Rcpp::List loglik_psi_cpp(const Eigen::MappedSparseMatrix<double> ZtZ, const Eigen::Map<Eigen::MatrixXd> XtZ, const Eigen::Map<Eigen::VectorXd> Zte, const Eigen::MappedSparseMatrix<double> Z, Eigen::VectorXd e, const Eigen::MappedSparseMatrix<double> H, const Eigen::MappedSparseMatrix<double> Psi_r, const double psi_r, const bool get_val, const bool get_score, const bool get_inf, const bool expected);
RcppExport SEXP _limestest_loglik_psi_cpp(SEXP ZtZSEXP, SEXP XtZSEXP, SEXP ZteSEXP, SEXP ZSEXP, SEXP eSEXP, SEXP HSEXP, SEXP Psi_rSEXP, SEXP psi_rSEXP, SEXP get_valSEXP, SEXP get_scoreSEXP, SEXP get_infSEXP, SEXP expectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type ZtZ(ZtZSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type XtZ(XtZSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Zte(ZteSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type e(eSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type H(HSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type Psi_r(Psi_rSEXP);
    Rcpp::traits::input_parameter< const double >::type psi_r(psi_rSEXP);
    Rcpp::traits::input_parameter< const bool >::type get_val(get_valSEXP);
    Rcpp::traits::input_parameter< const bool >::type get_score(get_scoreSEXP);
    Rcpp::traits::input_parameter< const bool >::type get_inf(get_infSEXP);
    Rcpp::traits::input_parameter< const bool >::type expected(expectedSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_psi_cpp(ZtZ, XtZ, Zte, Z, e, H, Psi_r, psi_r, get_val, get_score, get_inf, expected));
    return rcpp_result_gen;
END_RCPP
}
// res_llRcpp
Rcpp::List res_llRcpp(Eigen::Map<Eigen::MatrixXd> X, Eigen::Map<Eigen::VectorXd> Y, Eigen::MappedSparseMatrix<double> Z, Eigen::MappedSparseMatrix<double> H, Eigen::MappedSparseMatrix<double> Psi0, double psi0, bool lik, bool score, bool finf);
RcppExport SEXP _limestest_res_llRcpp(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP HSEXP, SEXP Psi0SEXP, SEXP psi0SEXP, SEXP likSEXP, SEXP scoreSEXP, SEXP finfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type H(HSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Psi0(Psi0SEXP);
    Rcpp::traits::input_parameter< double >::type psi0(psi0SEXP);
    Rcpp::traits::input_parameter< bool >::type lik(likSEXP);
    Rcpp::traits::input_parameter< bool >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< bool >::type finf(finfSEXP);
    rcpp_result_gen = Rcpp::wrap(res_llRcpp(X, Y, Z, H, Psi0, psi0, lik, score, finf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_limestest_Psi_from_H_cpp", (DL_FUNC) &_limestest_Psi_from_H_cpp, 2},
    {"_limestest_loglik_psi_cpp", (DL_FUNC) &_limestest_loglik_psi_cpp, 12},
    {"_limestest_res_llRcpp", (DL_FUNC) &_limestest_res_llRcpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_limestest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
