# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Psi_from_H_cpp
#'
#' Constructs the covariance matrix of the random effects
#'
#' @param psi_mr A vector of covariance parameter (see ?loglikelihood)
#' @param H Sparse matrix of derivatives of Psi with respect to elements of psi,
#'        \eqn{H = [H_1, \dots , H_{r - 1}]}, where \eqn{H_j = \partial \Psi / \partial \psi_j}.
#' @return The covariance matrix \eqn{\Psi}
Psi_from_H_cpp <- function(psi_mr, H) {
    .Call(`_limestest_Psi_from_H_cpp`, psi_mr, H)
}

#' Log-likelihood using RcppEigen
#'
#' Computes the log-likelihood, score vector, and information matrix
#' for the covariance parameter vector in a linear mixed effects model.
#'
#' @param Psi_r The \eqn{q\times q} covariance matrix of random effects (\eqn{\Psi}) divided by error
#'        variance, \eqn{\Psi_r = \Psi / \psi_r}.
#' @param psi_r The error variance \eqn{\psi_r > 0}.
#' @param H Sparse \eqn{q \times (qr - q)} matrix of horizontally concatenated
#'        derivatives of \eqn{\Psi} (see details) of class \code{dgCMatrix}.
#' @param e Vector of length \eqn{n} of errors, or residuals, \eqn{e = Y - X \beta}.
#' @param X Matrix of size \eqn{n \times p} of predictors, of class \code{matrix}.
#' @param Z Sparse \eqn{n \times q} random effect design matrix of class \code{dgCMatrix}.
#' @param XtX Precomputed matrix \code{crossprod(X)} of class \code{matrix}.
#' @param XtZ Precomputed matrix \code{crossprod(X, Z)} of class \code{matrix}.
#' @param ZtZ Precomputed matrix \code{crossprod(Z)} of class \code{dgCMatrix}.
#' @param get_val If \code{TRUE}, the value of the loglikelihood is computed.
#' @param get_score If \code{TRUE} the score vector is calculated.
#' @param get_inf If \code{TRUE}, an information matrix is calculated.
#' @param expected If \code{TRUE}, the expected information is calculated; otherwise
#' the observed, or negative Hessian of the loglikelihood.
#'
#' @return A list with components:
#' \item{value}{The value of the log-likelihood}
#' \item{score}{The score, or gradient of the log-likelihood, for \eqn{\psi}}
#' \item{inf_mat}{The information matrix for \eqn{\psi}}
#'
#' @details The model is \deqn{Y = X\beta + Z U + E,} where \eqn{U \sim N_q(0, \Psi)}
#' and \eqn{E \sim N_n(0, \psi_r I_n)}. The first \eqn{r - 1} elements of \eqn{\psi}
#' parameterize \eqn{\Psi}, while the \eqn{r}th and last element is the error
#' variance. It is assumed that \eqn{H_j = \partial \Psi / \partial \psi_j} is
#' a (usually sparse) matrix of zeros and ones, \eqn{j \in \{1, \dots, r - 1\}},
#' and that \eqn{\Psi = \sum_{j = 1}^{r - 1}\psi_j H_j}. Thus, \eqn{\psi_1, \dots, \psi_{r - 1}}
#' are variances and covariances of random effects.
#' The argument matrix \code{H} is \eqn{H = [H_1, \dots, H_{r - 1}]}.
#'
#' The fixed effects \eqn{\beta} affect the likelihood only through the
#' precomputed \eqn{e = Y - X\beta}.
#'
#' The information matrix includes both \eqn{\beta} and \eqn{\psi} parameters,
#' with dimensions \eqn{(p + r) \times (p + r)}.
#'
#' @useDynLib limestest, .registration=TRUE
#' @import Matrix
loglik <- function(Psi_r, psi_r, H, e, X, Z, XtX, XtZ, ZtZ, get_val = TRUE, get_score = TRUE, get_inf = TRUE, expected = TRUE) {
    .Call(`_limestest_loglik`, Psi_r, psi_r, H, e, X, Z, XtX, XtZ, ZtZ, get_val, get_score, get_inf, expected)
}

#' Restricted log-likelihood using RcppEigen
#'
#' Computes the restricted log-likelihood, score vector, and information matrix
#' for the covariance parameter vector in a linear mixed effects model.
#'
#' @param Psi_r The \eqn{q\times q} covariance matrix of random effects (\eqn{\Psi}) divided by error
#'        variance, \eqn{\Psi_r = \Psi / \psi_r} of class \code{dgCMatrix}.
#' @param psi_r The error variance \eqn{\psi_r > 0}.
#' @param H Sparse \eqn{q \times q(r - 1)} matrix of horizontally concatenated
#'        derivatives of \eqn{\Psi} (see details) of class \code{dgCMatrix}.
#' @param Y Vector of length \eqn{n} of responses, of class \code{numeric}.
#' @param X Matrix of size \eqn{n \times p} of predictors, of class \code{matrix}.
#' @param Z Sparse \eqn{n \times q} random effect design matrix of class \code{dgCMatrix}.
#' @param XtX Precomputed matrix \code{crossprod(X)} of class \code{matrix}.
#' @param XtZ Precomputed matrix \code{crossprod(X, Z)} of class \code{matrix}.
#' @param ZtZ Precomputed matrix \code{crossprod(Z)} of class \code{dgCMatrix}.
#' @param XtY Precomputed vector \code{crossprod(X, Y)} of class \code{numeric}.
#' @param ZtY Precomputed vector \code{crossprod(Z, Y)} of class \code{numeric}.
#' @param get_val If \code{TRUE}, the value of the loglikelihood is computed.
#' @param get_score If \code{TRUE} the score vector is calculated.
#' @param get_inf If \code{TRUE}, an information matrix is calculated.
#'
#' @return A list with components:
#' \item{value}{The value of the restricted log-likelihood}
#' \item{score}{The restricted score, or gradient of the restricted log-likelihood, for \eqn{\psi}}
#' \item{inf_mat}{The restricted information matrix for \eqn{\psi}}
#' \item{beta}{Partial maximizer of the regular likelihood in \eqn{\beta},
#'   \eqn{\tilde{\beta} = (X' \Sigma^{-1} X)^{-1} X' \Sigma^{-1}Y},
#'   where \eqn{\Sigma = Z\Psi Z' + \psi_r I_n}}
#' \item{I_b_inv_chol}{Cholesky root of the expected inverse information matrix
#'   for \eqn{\beta}, \eqn{I(\beta; \psi)^{-1} = (X' \Sigma^{-1} X)^{-1}}}
#'
#' @details The model is \deqn{Y = X\beta + Z U + E,} where \eqn{U \sim N_q(0, \Psi)}
#' and \eqn{E \sim N_n(0, \psi_r I_n)}. The first \eqn{r - 1} elements of \eqn{\psi}
#' parameterize \eqn{\Psi}, while the \eqn{r}th and last element is the error
#' variance. It is assumed that \eqn{H_j = \partial \Psi / \partial \psi_j} is
#' a (usually sparse) matrix of zeros and ones, \eqn{j \in \{1, \dots, r - 1\}},
#' and that \eqn{\Psi = \sum_{j = 1}^{r - 1}\psi_j H_j}. Thus, \eqn{\psi_1, \dots, \psi_{r - 1}}
#' are variances and covariances of random effects.
#' The argument matrix \code{H} is \eqn{H = [H_1, \dots, H_{r - 1}]}.
#'
#' The restricted likelihood integrates out the fixed effects \eqn{\beta}.
#'
#' @useDynLib limestest, .registration=TRUE
#' @import Matrix
res_loglik <- function(Psi_r, psi_r, H, Y, X, Z, XtX, XtZ, ZtZ, XtY, ZtY, get_val = TRUE, get_score = TRUE, get_inf = TRUE) {
    .Call(`_limestest_res_loglik`, Psi_r, psi_r, H, Y, X, Z, XtX, XtZ, ZtZ, XtY, ZtY, get_val, get_score, get_inf)
}

