# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_PsiRcpp <- function(psi, H) {
    .Call(`_limestest_get_PsiRcpp`, psi, H)
}

loglik_psiRcpp <- function(Z, e, H, Psi0, psi0, loglik = TRUE, score = TRUE, finf = TRUE, expected = TRUE) {
    .Call(`_limestest_loglik_psiRcpp`, Z, e, H, Psi0, psi0, loglik, score, finf, expected)
}

res_llRcpp <- function(X, Y, Z, H, Psi0, psi0, lik = TRUE, score = FALSE, finf = FALSE) {
    .Call(`_limestest_res_llRcpp`, X, Y, Z, H, Psi0, psi0, lik, score, finf)
}

