# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Psi_from_H_cpp
#'
#' Constructs the covariance matrix of the random effects
#'
#' @param psi_mr A vector of
#' @param H Matrix of derivatives of Psi with respect to elements of psi.
#'        Assumes H = [H_1, ... , H_r], where H_j is q by q.
#' @return The covariance matrix Psi
Psi_from_H_cpp <- function(psi_mr, H) {
    .Call(`_limestest_Psi_from_H_cpp`, psi_mr, H)
}

#' loglik_psi_cpp
#'
#' Calculates the log-likelihood, score vector and Fisher information matrix
#' for the variance parameter vector \code{psi} in a linear mixed effects model.
#' This function is implemented in C++ and is faster than the equivalent function \code{loglik_psi}
#'
#' @param ZtZ A matrix of fixed effects.
#' @param e The residual vector.
#' @param H Matrix of derivatives of Psi with respect to elements of psi.
#'        Assumes H = [H_1, ... , H_r], where H_j is q by q.
#' @param Psi_r Coavariance matrix of random effects (Psi) divided by error
#'        variance psi_r, with dimensions q by q.
#' @param psi_r The error variance
#' @param loglik If \code{TRUE} (default), the log-likelihood will be calculated.
#' @param score If \code{TRUE} (default), the score vector will be calculated.
#' @param finf If \code{TRUE} (default), the Fisher information matrix will be calculated.
#' @param expected If \code{TRUE} (detault), return expected information;
#'        otherwise observed.
#'
#' @return A list with components:
#' \item{ll}{The log-likelihood.}
#' \item{score}{The score vector.}
#' \item{finf}{The Fisher information matrix.}
#'
#' @useDynLib limestest, .registration=TRUE
loglik_psi_cpp <- function(ZtZ, XtZ, Zte, Z, e, H, Psi_r, psi_r, get_val = TRUE, get_score = TRUE, get_inf = TRUE, expected = TRUE) {
    .Call(`_limestest_loglik_psi_cpp`, ZtZ, XtZ, Zte, Z, e, H, Psi_r, psi_r, get_val, get_score, get_inf, expected)
}

#' Compute Restricted Likelihood, Score and Information
#'
#' Computes the restricted (residual) likelihood, score, and information matrix
#' for the variance parameter \code{psi} a linear mixed effects model
#'
#' @param X An n x p matrix of the design matrix of fixed effects.
#' @param Y An n x 1 vector of the response variable.
#' @param Z An n x q matrix of the design matrix of random effects.
#' @param H A q x rq matrix, where H = [H_1, ..., H_r], with H_j being the
#' derivative of Psi with respect to psi_j
#' @param Psi_r The covariance matrix of the random effects (Psi) divided by the
#' error variance (psi_r)
#' @param psi_r A scalar value of the error variance.
#' @param lik If \code{TRUE} (default), the log-likelihood will be computed.
#' @param score If \code{TRUE} (default), the score vector will be computed.
#' @param finf If \code{TRUE} (default), the Fisher information matrix will be
#' computed.
#'
#' @return A list with elements:
#' \describe{
#' \item{ll}{A scalar value of the restricted log-likelihood.}
#' \item{score}{A (r + 1) x 1 vector of the restricted score of the variance parameters.}
#' \item{finf}{A (r + 1) x (r + 1) matrix of the restricted  information of the
#' variance parameters.}
#' \item{beta}{Maximum likelihood estimate for the fixed effects parameter}
#' \item{I_b_inv_chol}{Inverse of the Cholesky root of the information matrix for the fixed effects parameter beta}
#' }
#' @import Matrix
res_llRcpp <- function(Y, X, Z, XtY, ZtY, XtX, XtZ, ZtZ, H, Psi_r, psi_r, get_val = TRUE, get_score = TRUE, get_inf = TRUE, expected = TRUE) {
    .Call(`_limestest_res_llRcpp`, Y, X, Z, XtY, ZtY, XtX, XtZ, ZtZ, H, Psi_r, psi_r, get_val, get_score, get_inf, expected)
}

